site_name: auth-cookie-pair
repo_url: https://github.com/alxevvv/auth-cookie-pair
site_url: https://alxevvv.github.io/auth-cookie-pair
site_description: This is a template repository for Python projects that use PDM for their dependency management.
site_author: Vladislav Alexeev
edit_uri: edit/main/docs/
repo_name: alxevvv/auth-cookie-pair
copyright: Maintained by Vladislav Alexeev.

nav:
  - Home: index.md
  - Modules: modules.md
  - License: license.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')

use_directory_urls: false

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alxevvv/auth-cookie-pair
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/auth-cookie-pair

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
